Squashed commit of the following:
commit e9814170361037985d6e6e4ced89972ab41f0af2
Author: AreebKhan619 <areebkhan619@gmail.com>
Date:   Mon Jan 30 10:29:10 2023 +0530

    Update package.json

commit 71a4e7b6153db427bd9a33e2b9e7d1590dd2b1d2
Author: AreebKhan619 <areebkhan619@gmail.com>
Date:   Mon Jan 30 10:13:02 2023 +0530

    Update buildJwt

diff --git a/buildJwt b/buildJwt
--- a/buildJwt
+++ b/buildJwt
@@ -1,3 +1,38 @@
 #!/bin/bash
 
-cd ./app && npm run build
+GREEN='\033[32m'
+RED='\033[0;31m'
+NC='\033[0m' # No color
+
+cd ./app
+
+# build the jwt-decoder
+echo -e "${GREEN}Building jwt-decoder...${NC}"
+
+# npm run build >/dev/null 2>/dev/null
+npm run build
+doesBuild=$?
+
+if [ $doesBuild -ne 0 ]
+then
+  echo -e "${RED}JWT Decoder build failed.${NC}"
+  exit 1
+fi
+
+echo -e "${GREEN}JWT Deocder built successfully.${NC}"
+
+
+projectDir=$(pwd)
+cd ..
+
+echo -e "${projectDir}";
+
+# check if the jet directory exists
+if [ ! -d ../supertokens-backend-website/app/jwt-decoder ]; then
+mkdir ../supertokens-backend-website/app/jwt-decoder
+fi
+
+# remove all the files of old jwt-decoder and replace with newly built jwt-decoder
+rm -rf ../supertokens-backend-website/app/jwt-decoder/*
+cp -r $projectDir/build/* ../supertokens-backend-website/app/jwt-decoder/
+echo -e "${GREEN}JWT Decoder moved to supertokens-backend-website.${NC}"
